/*
Elba Public API

Testing ElbaAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package elba

import (
	"context"
	openapiclient "github.com/archaron/elba-api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_elba_ElbaAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ElbaAPIService OrganizationsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ElbaAPI.OrganizationsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
