/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductNameToCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductNameToCreate{}

// ProductNameToCreate struct for ProductNameToCreate
type ProductNameToCreate struct {
	// Название товара
	Name string `json:"name"`
	// Название товара является основным
	IsMain bool `json:"isMain"`
}

type _ProductNameToCreate ProductNameToCreate

// NewProductNameToCreate instantiates a new ProductNameToCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductNameToCreate(name string, isMain bool) *ProductNameToCreate {
	this := ProductNameToCreate{}
	this.Name = name
	this.IsMain = isMain
	return &this
}

// NewProductNameToCreateWithDefaults instantiates a new ProductNameToCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductNameToCreateWithDefaults() *ProductNameToCreate {
	this := ProductNameToCreate{}
	return &this
}

// GetName returns the Name field value
func (o *ProductNameToCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductNameToCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductNameToCreate) SetName(v string) {
	o.Name = v
}

// GetIsMain returns the IsMain field value
func (o *ProductNameToCreate) GetIsMain() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMain
}

// GetIsMainOk returns a tuple with the IsMain field value
// and a boolean to check if the value has been set.
func (o *ProductNameToCreate) GetIsMainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMain, true
}

// SetIsMain sets field value
func (o *ProductNameToCreate) SetIsMain(v bool) {
	o.IsMain = v
}

func (o ProductNameToCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductNameToCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["isMain"] = o.IsMain
	return toSerialize, nil
}

func (o *ProductNameToCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"isMain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductNameToCreate := _ProductNameToCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductNameToCreate)

	if err != nil {
		return err
	}

	*o = ProductNameToCreate(varProductNameToCreate)

	return err
}

type NullableProductNameToCreate struct {
	value *ProductNameToCreate
	isSet bool
}

func (v NullableProductNameToCreate) Get() *ProductNameToCreate {
	return v.value
}

func (v *NullableProductNameToCreate) Set(val *ProductNameToCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableProductNameToCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableProductNameToCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductNameToCreate(val *ProductNameToCreate) *NullableProductNameToCreate {
	return &NullableProductNameToCreate{value: val, isSet: true}
}

func (v NullableProductNameToCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductNameToCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


