/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductUnitToUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductUnitToUpdate{}

// ProductUnitToUpdate struct for ProductUnitToUpdate
type ProductUnitToUpdate struct {
	// Идентификатор единицы измерения
	Id NullableString `json:"id,omitempty"`
	// Единица измерения является основной
	IsMain bool `json:"isMain"`
	// Название единицы измерения
	Name string `json:"name"`
	// Соотношение единицы измерения с основной
	Ratio int32 `json:"ratio"`
}

type _ProductUnitToUpdate ProductUnitToUpdate

// NewProductUnitToUpdate instantiates a new ProductUnitToUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductUnitToUpdate(isMain bool, name string, ratio int32) *ProductUnitToUpdate {
	this := ProductUnitToUpdate{}
	this.IsMain = isMain
	this.Name = name
	this.Ratio = ratio
	return &this
}

// NewProductUnitToUpdateWithDefaults instantiates a new ProductUnitToUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductUnitToUpdateWithDefaults() *ProductUnitToUpdate {
	this := ProductUnitToUpdate{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductUnitToUpdate) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductUnitToUpdate) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ProductUnitToUpdate) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ProductUnitToUpdate) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *ProductUnitToUpdate) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ProductUnitToUpdate) UnsetId() {
	o.Id.Unset()
}

// GetIsMain returns the IsMain field value
func (o *ProductUnitToUpdate) GetIsMain() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMain
}

// GetIsMainOk returns a tuple with the IsMain field value
// and a boolean to check if the value has been set.
func (o *ProductUnitToUpdate) GetIsMainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMain, true
}

// SetIsMain sets field value
func (o *ProductUnitToUpdate) SetIsMain(v bool) {
	o.IsMain = v
}

// GetName returns the Name field value
func (o *ProductUnitToUpdate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductUnitToUpdate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductUnitToUpdate) SetName(v string) {
	o.Name = v
}

// GetRatio returns the Ratio field value
func (o *ProductUnitToUpdate) GetRatio() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ratio
}

// GetRatioOk returns a tuple with the Ratio field value
// and a boolean to check if the value has been set.
func (o *ProductUnitToUpdate) GetRatioOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ratio, true
}

// SetRatio sets field value
func (o *ProductUnitToUpdate) SetRatio(v int32) {
	o.Ratio = v
}

func (o ProductUnitToUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductUnitToUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	toSerialize["isMain"] = o.IsMain
	toSerialize["name"] = o.Name
	toSerialize["ratio"] = o.Ratio
	return toSerialize, nil
}

func (o *ProductUnitToUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isMain",
		"name",
		"ratio",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductUnitToUpdate := _ProductUnitToUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductUnitToUpdate)

	if err != nil {
		return err
	}

	*o = ProductUnitToUpdate(varProductUnitToUpdate)

	return err
}

type NullableProductUnitToUpdate struct {
	value *ProductUnitToUpdate
	isSet bool
}

func (v NullableProductUnitToUpdate) Get() *ProductUnitToUpdate {
	return v.value
}

func (v *NullableProductUnitToUpdate) Set(val *ProductUnitToUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableProductUnitToUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableProductUnitToUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductUnitToUpdate(val *ProductUnitToUpdate) *NullableProductUnitToUpdate {
	return &NullableProductUnitToUpdate{value: val, isSet: true}
}

func (v NullableProductUnitToUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductUnitToUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


