/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductNameToUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductNameToUpdate{}

// ProductNameToUpdate struct for ProductNameToUpdate
type ProductNameToUpdate struct {
	// Идентификатор названия товара
	Id NullableString `json:"id,omitempty"`
	// Название товара
	Name string `json:"name"`
	// Название товара является основным
	IsMain bool `json:"isMain"`
}

type _ProductNameToUpdate ProductNameToUpdate

// NewProductNameToUpdate instantiates a new ProductNameToUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductNameToUpdate(name string, isMain bool) *ProductNameToUpdate {
	this := ProductNameToUpdate{}
	this.Name = name
	this.IsMain = isMain
	return &this
}

// NewProductNameToUpdateWithDefaults instantiates a new ProductNameToUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductNameToUpdateWithDefaults() *ProductNameToUpdate {
	this := ProductNameToUpdate{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductNameToUpdate) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductNameToUpdate) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ProductNameToUpdate) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ProductNameToUpdate) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *ProductNameToUpdate) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ProductNameToUpdate) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value
func (o *ProductNameToUpdate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductNameToUpdate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductNameToUpdate) SetName(v string) {
	o.Name = v
}

// GetIsMain returns the IsMain field value
func (o *ProductNameToUpdate) GetIsMain() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMain
}

// GetIsMainOk returns a tuple with the IsMain field value
// and a boolean to check if the value has been set.
func (o *ProductNameToUpdate) GetIsMainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMain, true
}

// SetIsMain sets field value
func (o *ProductNameToUpdate) SetIsMain(v bool) {
	o.IsMain = v
}

func (o ProductNameToUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductNameToUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["isMain"] = o.IsMain
	return toSerialize, nil
}

func (o *ProductNameToUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"isMain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductNameToUpdate := _ProductNameToUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductNameToUpdate)

	if err != nil {
		return err
	}

	*o = ProductNameToUpdate(varProductNameToUpdate)

	return err
}

type NullableProductNameToUpdate struct {
	value *ProductNameToUpdate
	isSet bool
}

func (v NullableProductNameToUpdate) Get() *ProductNameToUpdate {
	return v.value
}

func (v *NullableProductNameToUpdate) Set(val *ProductNameToUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableProductNameToUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableProductNameToUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductNameToUpdate(val *ProductNameToUpdate) *NullableProductNameToUpdate {
	return &NullableProductNameToUpdate{value: val, isSet: true}
}

func (v NullableProductNameToUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductNameToUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


