/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateUniversalTransferDocumentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUniversalTransferDocumentRequest{}

// CreateUniversalTransferDocumentRequest struct for CreateUniversalTransferDocumentRequest
type CreateUniversalTransferDocumentRequest struct {
	// Номер УПД. Если номер не указан, то номер будет сгенерирован Эльбой
	Number NullableString `json:"number,omitempty"`
	// Дата УПД
	Date string `json:"date"`
	// Идентификатор банковского счёта
	BankAccountId NullableString `json:"bankAccountId,omitempty"`
	// Идентификатор контрагента
	ContractorId NullableString `json:"contractorId,omitempty"`
	// Цена за единицу товара включает в себя НДС
	SumsWithNDS NullableBool `json:"sumsWithNDS,omitempty"`
	// Идентификатор грузополучателя
	ConsigneeId NullableString `json:"consigneeId,omitempty"`
	// Продаю прослеживаемый товар
	WithProductTracing NullableBool `json:"withProductTracing,omitempty"`
	// Статус  status1 (Со счётом-фактурой, то есть с НДС)  status2 (Без счёта-фактуры)
	Status UniversalTransferDocumentStatus `json:"status"`
	// Идентификатор госконтракта
	StateContractIdentifier NullableString `json:"stateContractIdentifier,omitempty"`
	// Основание
	ReasonName NullableString `json:"reasonName,omitempty"`
	// Дата основания
	ReasonDate NullableString `json:"reasonDate,omitempty"`
	// Выставить УПД со скидкой
	WithDiscount NullableBool `json:"withDiscount,omitempty"`
	// Фактурная часть
	WarehouseItems []UniversalTransferDocumentItemToCreate `json:"warehouseItems,omitempty"`
}

type _CreateUniversalTransferDocumentRequest CreateUniversalTransferDocumentRequest

// NewCreateUniversalTransferDocumentRequest instantiates a new CreateUniversalTransferDocumentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUniversalTransferDocumentRequest(date string, status UniversalTransferDocumentStatus) *CreateUniversalTransferDocumentRequest {
	this := CreateUniversalTransferDocumentRequest{}
	this.Date = date
	this.Status = status
	return &this
}

// NewCreateUniversalTransferDocumentRequestWithDefaults instantiates a new CreateUniversalTransferDocumentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUniversalTransferDocumentRequestWithDefaults() *CreateUniversalTransferDocumentRequest {
	this := CreateUniversalTransferDocumentRequest{}
	return &this
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetNumber() string {
	if o == nil || IsNil(o.Number.Get()) {
		var ret string
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableString and assigns it to the Number field.
func (o *CreateUniversalTransferDocumentRequest) SetNumber(v string) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetNumber() {
	o.Number.Unset()
}

// GetDate returns the Date field value
func (o *CreateUniversalTransferDocumentRequest) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *CreateUniversalTransferDocumentRequest) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *CreateUniversalTransferDocumentRequest) SetDate(v string) {
	o.Date = v
}

// GetBankAccountId returns the BankAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetBankAccountId() string {
	if o == nil || IsNil(o.BankAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.BankAccountId.Get()
}

// GetBankAccountIdOk returns a tuple with the BankAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetBankAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BankAccountId.Get(), o.BankAccountId.IsSet()
}

// HasBankAccountId returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasBankAccountId() bool {
	if o != nil && o.BankAccountId.IsSet() {
		return true
	}

	return false
}

// SetBankAccountId gets a reference to the given NullableString and assigns it to the BankAccountId field.
func (o *CreateUniversalTransferDocumentRequest) SetBankAccountId(v string) {
	o.BankAccountId.Set(&v)
}
// SetBankAccountIdNil sets the value for BankAccountId to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetBankAccountIdNil() {
	o.BankAccountId.Set(nil)
}

// UnsetBankAccountId ensures that no value is present for BankAccountId, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetBankAccountId() {
	o.BankAccountId.Unset()
}

// GetContractorId returns the ContractorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetContractorId() string {
	if o == nil || IsNil(o.ContractorId.Get()) {
		var ret string
		return ret
	}
	return *o.ContractorId.Get()
}

// GetContractorIdOk returns a tuple with the ContractorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetContractorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContractorId.Get(), o.ContractorId.IsSet()
}

// HasContractorId returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasContractorId() bool {
	if o != nil && o.ContractorId.IsSet() {
		return true
	}

	return false
}

// SetContractorId gets a reference to the given NullableString and assigns it to the ContractorId field.
func (o *CreateUniversalTransferDocumentRequest) SetContractorId(v string) {
	o.ContractorId.Set(&v)
}
// SetContractorIdNil sets the value for ContractorId to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetContractorIdNil() {
	o.ContractorId.Set(nil)
}

// UnsetContractorId ensures that no value is present for ContractorId, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetContractorId() {
	o.ContractorId.Unset()
}

// GetSumsWithNDS returns the SumsWithNDS field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetSumsWithNDS() bool {
	if o == nil || IsNil(o.SumsWithNDS.Get()) {
		var ret bool
		return ret
	}
	return *o.SumsWithNDS.Get()
}

// GetSumsWithNDSOk returns a tuple with the SumsWithNDS field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetSumsWithNDSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SumsWithNDS.Get(), o.SumsWithNDS.IsSet()
}

// HasSumsWithNDS returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasSumsWithNDS() bool {
	if o != nil && o.SumsWithNDS.IsSet() {
		return true
	}

	return false
}

// SetSumsWithNDS gets a reference to the given NullableBool and assigns it to the SumsWithNDS field.
func (o *CreateUniversalTransferDocumentRequest) SetSumsWithNDS(v bool) {
	o.SumsWithNDS.Set(&v)
}
// SetSumsWithNDSNil sets the value for SumsWithNDS to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetSumsWithNDSNil() {
	o.SumsWithNDS.Set(nil)
}

// UnsetSumsWithNDS ensures that no value is present for SumsWithNDS, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetSumsWithNDS() {
	o.SumsWithNDS.Unset()
}

// GetConsigneeId returns the ConsigneeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetConsigneeId() string {
	if o == nil || IsNil(o.ConsigneeId.Get()) {
		var ret string
		return ret
	}
	return *o.ConsigneeId.Get()
}

// GetConsigneeIdOk returns a tuple with the ConsigneeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetConsigneeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsigneeId.Get(), o.ConsigneeId.IsSet()
}

// HasConsigneeId returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasConsigneeId() bool {
	if o != nil && o.ConsigneeId.IsSet() {
		return true
	}

	return false
}

// SetConsigneeId gets a reference to the given NullableString and assigns it to the ConsigneeId field.
func (o *CreateUniversalTransferDocumentRequest) SetConsigneeId(v string) {
	o.ConsigneeId.Set(&v)
}
// SetConsigneeIdNil sets the value for ConsigneeId to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetConsigneeIdNil() {
	o.ConsigneeId.Set(nil)
}

// UnsetConsigneeId ensures that no value is present for ConsigneeId, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetConsigneeId() {
	o.ConsigneeId.Unset()
}

// GetWithProductTracing returns the WithProductTracing field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetWithProductTracing() bool {
	if o == nil || IsNil(o.WithProductTracing.Get()) {
		var ret bool
		return ret
	}
	return *o.WithProductTracing.Get()
}

// GetWithProductTracingOk returns a tuple with the WithProductTracing field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetWithProductTracingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WithProductTracing.Get(), o.WithProductTracing.IsSet()
}

// HasWithProductTracing returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasWithProductTracing() bool {
	if o != nil && o.WithProductTracing.IsSet() {
		return true
	}

	return false
}

// SetWithProductTracing gets a reference to the given NullableBool and assigns it to the WithProductTracing field.
func (o *CreateUniversalTransferDocumentRequest) SetWithProductTracing(v bool) {
	o.WithProductTracing.Set(&v)
}
// SetWithProductTracingNil sets the value for WithProductTracing to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetWithProductTracingNil() {
	o.WithProductTracing.Set(nil)
}

// UnsetWithProductTracing ensures that no value is present for WithProductTracing, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetWithProductTracing() {
	o.WithProductTracing.Unset()
}

// GetStatus returns the Status field value
func (o *CreateUniversalTransferDocumentRequest) GetStatus() UniversalTransferDocumentStatus {
	if o == nil {
		var ret UniversalTransferDocumentStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateUniversalTransferDocumentRequest) GetStatusOk() (*UniversalTransferDocumentStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateUniversalTransferDocumentRequest) SetStatus(v UniversalTransferDocumentStatus) {
	o.Status = v
}

// GetStateContractIdentifier returns the StateContractIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetStateContractIdentifier() string {
	if o == nil || IsNil(o.StateContractIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.StateContractIdentifier.Get()
}

// GetStateContractIdentifierOk returns a tuple with the StateContractIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetStateContractIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StateContractIdentifier.Get(), o.StateContractIdentifier.IsSet()
}

// HasStateContractIdentifier returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasStateContractIdentifier() bool {
	if o != nil && o.StateContractIdentifier.IsSet() {
		return true
	}

	return false
}

// SetStateContractIdentifier gets a reference to the given NullableString and assigns it to the StateContractIdentifier field.
func (o *CreateUniversalTransferDocumentRequest) SetStateContractIdentifier(v string) {
	o.StateContractIdentifier.Set(&v)
}
// SetStateContractIdentifierNil sets the value for StateContractIdentifier to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetStateContractIdentifierNil() {
	o.StateContractIdentifier.Set(nil)
}

// UnsetStateContractIdentifier ensures that no value is present for StateContractIdentifier, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetStateContractIdentifier() {
	o.StateContractIdentifier.Unset()
}

// GetReasonName returns the ReasonName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetReasonName() string {
	if o == nil || IsNil(o.ReasonName.Get()) {
		var ret string
		return ret
	}
	return *o.ReasonName.Get()
}

// GetReasonNameOk returns a tuple with the ReasonName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetReasonNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReasonName.Get(), o.ReasonName.IsSet()
}

// HasReasonName returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasReasonName() bool {
	if o != nil && o.ReasonName.IsSet() {
		return true
	}

	return false
}

// SetReasonName gets a reference to the given NullableString and assigns it to the ReasonName field.
func (o *CreateUniversalTransferDocumentRequest) SetReasonName(v string) {
	o.ReasonName.Set(&v)
}
// SetReasonNameNil sets the value for ReasonName to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetReasonNameNil() {
	o.ReasonName.Set(nil)
}

// UnsetReasonName ensures that no value is present for ReasonName, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetReasonName() {
	o.ReasonName.Unset()
}

// GetReasonDate returns the ReasonDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetReasonDate() string {
	if o == nil || IsNil(o.ReasonDate.Get()) {
		var ret string
		return ret
	}
	return *o.ReasonDate.Get()
}

// GetReasonDateOk returns a tuple with the ReasonDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetReasonDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReasonDate.Get(), o.ReasonDate.IsSet()
}

// HasReasonDate returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasReasonDate() bool {
	if o != nil && o.ReasonDate.IsSet() {
		return true
	}

	return false
}

// SetReasonDate gets a reference to the given NullableString and assigns it to the ReasonDate field.
func (o *CreateUniversalTransferDocumentRequest) SetReasonDate(v string) {
	o.ReasonDate.Set(&v)
}
// SetReasonDateNil sets the value for ReasonDate to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetReasonDateNil() {
	o.ReasonDate.Set(nil)
}

// UnsetReasonDate ensures that no value is present for ReasonDate, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetReasonDate() {
	o.ReasonDate.Unset()
}

// GetWithDiscount returns the WithDiscount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetWithDiscount() bool {
	if o == nil || IsNil(o.WithDiscount.Get()) {
		var ret bool
		return ret
	}
	return *o.WithDiscount.Get()
}

// GetWithDiscountOk returns a tuple with the WithDiscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetWithDiscountOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WithDiscount.Get(), o.WithDiscount.IsSet()
}

// HasWithDiscount returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasWithDiscount() bool {
	if o != nil && o.WithDiscount.IsSet() {
		return true
	}

	return false
}

// SetWithDiscount gets a reference to the given NullableBool and assigns it to the WithDiscount field.
func (o *CreateUniversalTransferDocumentRequest) SetWithDiscount(v bool) {
	o.WithDiscount.Set(&v)
}
// SetWithDiscountNil sets the value for WithDiscount to be an explicit nil
func (o *CreateUniversalTransferDocumentRequest) SetWithDiscountNil() {
	o.WithDiscount.Set(nil)
}

// UnsetWithDiscount ensures that no value is present for WithDiscount, not even an explicit nil
func (o *CreateUniversalTransferDocumentRequest) UnsetWithDiscount() {
	o.WithDiscount.Unset()
}

// GetWarehouseItems returns the WarehouseItems field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateUniversalTransferDocumentRequest) GetWarehouseItems() []UniversalTransferDocumentItemToCreate {
	if o == nil {
		var ret []UniversalTransferDocumentItemToCreate
		return ret
	}
	return o.WarehouseItems
}

// GetWarehouseItemsOk returns a tuple with the WarehouseItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUniversalTransferDocumentRequest) GetWarehouseItemsOk() ([]UniversalTransferDocumentItemToCreate, bool) {
	if o == nil || IsNil(o.WarehouseItems) {
		return nil, false
	}
	return o.WarehouseItems, true
}

// HasWarehouseItems returns a boolean if a field has been set.
func (o *CreateUniversalTransferDocumentRequest) HasWarehouseItems() bool {
	if o != nil && !IsNil(o.WarehouseItems) {
		return true
	}

	return false
}

// SetWarehouseItems gets a reference to the given []UniversalTransferDocumentItemToCreate and assigns it to the WarehouseItems field.
func (o *CreateUniversalTransferDocumentRequest) SetWarehouseItems(v []UniversalTransferDocumentItemToCreate) {
	o.WarehouseItems = v
}

func (o CreateUniversalTransferDocumentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUniversalTransferDocumentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	toSerialize["date"] = o.Date
	if o.BankAccountId.IsSet() {
		toSerialize["bankAccountId"] = o.BankAccountId.Get()
	}
	if o.ContractorId.IsSet() {
		toSerialize["contractorId"] = o.ContractorId.Get()
	}
	if o.SumsWithNDS.IsSet() {
		toSerialize["sumsWithNDS"] = o.SumsWithNDS.Get()
	}
	if o.ConsigneeId.IsSet() {
		toSerialize["consigneeId"] = o.ConsigneeId.Get()
	}
	if o.WithProductTracing.IsSet() {
		toSerialize["withProductTracing"] = o.WithProductTracing.Get()
	}
	toSerialize["status"] = o.Status
	if o.StateContractIdentifier.IsSet() {
		toSerialize["stateContractIdentifier"] = o.StateContractIdentifier.Get()
	}
	if o.ReasonName.IsSet() {
		toSerialize["reasonName"] = o.ReasonName.Get()
	}
	if o.ReasonDate.IsSet() {
		toSerialize["reasonDate"] = o.ReasonDate.Get()
	}
	if o.WithDiscount.IsSet() {
		toSerialize["withDiscount"] = o.WithDiscount.Get()
	}
	if o.WarehouseItems != nil {
		toSerialize["warehouseItems"] = o.WarehouseItems
	}
	return toSerialize, nil
}

func (o *CreateUniversalTransferDocumentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUniversalTransferDocumentRequest := _CreateUniversalTransferDocumentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUniversalTransferDocumentRequest)

	if err != nil {
		return err
	}

	*o = CreateUniversalTransferDocumentRequest(varCreateUniversalTransferDocumentRequest)

	return err
}

type NullableCreateUniversalTransferDocumentRequest struct {
	value *CreateUniversalTransferDocumentRequest
	isSet bool
}

func (v NullableCreateUniversalTransferDocumentRequest) Get() *CreateUniversalTransferDocumentRequest {
	return v.value
}

func (v *NullableCreateUniversalTransferDocumentRequest) Set(val *CreateUniversalTransferDocumentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUniversalTransferDocumentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUniversalTransferDocumentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUniversalTransferDocumentRequest(val *CreateUniversalTransferDocumentRequest) *NullableCreateUniversalTransferDocumentRequest {
	return &NullableCreateUniversalTransferDocumentRequest{value: val, isSet: true}
}

func (v NullableCreateUniversalTransferDocumentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUniversalTransferDocumentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


