/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductName{}

// ProductName struct for ProductName
type ProductName struct {
	// Идентификатор названия товара
	Id string `json:"id"`
	// Название товара
	Name string `json:"name"`
	// Название товара является основным
	IsMain bool `json:"isMain"`
}

type _ProductName ProductName

// NewProductName instantiates a new ProductName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductName(id string, name string, isMain bool) *ProductName {
	this := ProductName{}
	this.Id = id
	this.Name = name
	this.IsMain = isMain
	return &this
}

// NewProductNameWithDefaults instantiates a new ProductName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductNameWithDefaults() *ProductName {
	this := ProductName{}
	return &this
}

// GetId returns the Id field value
func (o *ProductName) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProductName) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProductName) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ProductName) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductName) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductName) SetName(v string) {
	o.Name = v
}

// GetIsMain returns the IsMain field value
func (o *ProductName) GetIsMain() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMain
}

// GetIsMainOk returns a tuple with the IsMain field value
// and a boolean to check if the value has been set.
func (o *ProductName) GetIsMainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMain, true
}

// SetIsMain sets field value
func (o *ProductName) SetIsMain(v bool) {
	o.IsMain = v
}

func (o ProductName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["isMain"] = o.IsMain
	return toSerialize, nil
}

func (o *ProductName) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"isMain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductName := _ProductName{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductName)

	if err != nil {
		return err
	}

	*o = ProductName(varProductName)

	return err
}

type NullableProductName struct {
	value *ProductName
	isSet bool
}

func (v NullableProductName) Get() *ProductName {
	return v.value
}

func (v *NullableProductName) Set(val *ProductName) {
	v.value = val
	v.isSet = true
}

func (v NullableProductName) IsSet() bool {
	return v.isSet
}

func (v *NullableProductName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductName(val *ProductName) *NullableProductName {
	return &NullableProductName{value: val, isSet: true}
}

func (v NullableProductName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


