/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FoundContractor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FoundContractor{}

// FoundContractor struct for FoundContractor
type FoundContractor struct {
	// Идентификатор созданного контрагента
	Id string `json:"id"`
	// Полное название контрагента
	Name string `json:"name"`
	// Краткое название контрагента
	ShortName NullableString `json:"shortName,omitempty"`
	// ИНН
	Inn NullableString `json:"inn,omitempty"`
	// КПП
	Kpp NullableString `json:"kpp,omitempty"`
	// Юридический адрес
	Address NullableString `json:"address,omitempty"`
}

type _FoundContractor FoundContractor

// NewFoundContractor instantiates a new FoundContractor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFoundContractor(id string, name string) *FoundContractor {
	this := FoundContractor{}
	this.Id = id
	this.Name = name
	return &this
}

// NewFoundContractorWithDefaults instantiates a new FoundContractor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFoundContractorWithDefaults() *FoundContractor {
	this := FoundContractor{}
	return &this
}

// GetId returns the Id field value
func (o *FoundContractor) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FoundContractor) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FoundContractor) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *FoundContractor) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FoundContractor) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FoundContractor) SetName(v string) {
	o.Name = v
}

// GetShortName returns the ShortName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FoundContractor) GetShortName() string {
	if o == nil || IsNil(o.ShortName.Get()) {
		var ret string
		return ret
	}
	return *o.ShortName.Get()
}

// GetShortNameOk returns a tuple with the ShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FoundContractor) GetShortNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShortName.Get(), o.ShortName.IsSet()
}

// HasShortName returns a boolean if a field has been set.
func (o *FoundContractor) HasShortName() bool {
	if o != nil && o.ShortName.IsSet() {
		return true
	}

	return false
}

// SetShortName gets a reference to the given NullableString and assigns it to the ShortName field.
func (o *FoundContractor) SetShortName(v string) {
	o.ShortName.Set(&v)
}
// SetShortNameNil sets the value for ShortName to be an explicit nil
func (o *FoundContractor) SetShortNameNil() {
	o.ShortName.Set(nil)
}

// UnsetShortName ensures that no value is present for ShortName, not even an explicit nil
func (o *FoundContractor) UnsetShortName() {
	o.ShortName.Unset()
}

// GetInn returns the Inn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FoundContractor) GetInn() string {
	if o == nil || IsNil(o.Inn.Get()) {
		var ret string
		return ret
	}
	return *o.Inn.Get()
}

// GetInnOk returns a tuple with the Inn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FoundContractor) GetInnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Inn.Get(), o.Inn.IsSet()
}

// HasInn returns a boolean if a field has been set.
func (o *FoundContractor) HasInn() bool {
	if o != nil && o.Inn.IsSet() {
		return true
	}

	return false
}

// SetInn gets a reference to the given NullableString and assigns it to the Inn field.
func (o *FoundContractor) SetInn(v string) {
	o.Inn.Set(&v)
}
// SetInnNil sets the value for Inn to be an explicit nil
func (o *FoundContractor) SetInnNil() {
	o.Inn.Set(nil)
}

// UnsetInn ensures that no value is present for Inn, not even an explicit nil
func (o *FoundContractor) UnsetInn() {
	o.Inn.Unset()
}

// GetKpp returns the Kpp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FoundContractor) GetKpp() string {
	if o == nil || IsNil(o.Kpp.Get()) {
		var ret string
		return ret
	}
	return *o.Kpp.Get()
}

// GetKppOk returns a tuple with the Kpp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FoundContractor) GetKppOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Kpp.Get(), o.Kpp.IsSet()
}

// HasKpp returns a boolean if a field has been set.
func (o *FoundContractor) HasKpp() bool {
	if o != nil && o.Kpp.IsSet() {
		return true
	}

	return false
}

// SetKpp gets a reference to the given NullableString and assigns it to the Kpp field.
func (o *FoundContractor) SetKpp(v string) {
	o.Kpp.Set(&v)
}
// SetKppNil sets the value for Kpp to be an explicit nil
func (o *FoundContractor) SetKppNil() {
	o.Kpp.Set(nil)
}

// UnsetKpp ensures that no value is present for Kpp, not even an explicit nil
func (o *FoundContractor) UnsetKpp() {
	o.Kpp.Unset()
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FoundContractor) GetAddress() string {
	if o == nil || IsNil(o.Address.Get()) {
		var ret string
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FoundContractor) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *FoundContractor) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableString and assigns it to the Address field.
func (o *FoundContractor) SetAddress(v string) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *FoundContractor) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *FoundContractor) UnsetAddress() {
	o.Address.Unset()
}

func (o FoundContractor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FoundContractor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if o.ShortName.IsSet() {
		toSerialize["shortName"] = o.ShortName.Get()
	}
	if o.Inn.IsSet() {
		toSerialize["inn"] = o.Inn.Get()
	}
	if o.Kpp.IsSet() {
		toSerialize["kpp"] = o.Kpp.Get()
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	return toSerialize, nil
}

func (o *FoundContractor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFoundContractor := _FoundContractor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFoundContractor)

	if err != nil {
		return err
	}

	*o = FoundContractor(varFoundContractor)

	return err
}

type NullableFoundContractor struct {
	value *FoundContractor
	isSet bool
}

func (v NullableFoundContractor) Get() *FoundContractor {
	return v.value
}

func (v *NullableFoundContractor) Set(val *FoundContractor) {
	v.value = val
	v.isSet = true
}

func (v NullableFoundContractor) IsSet() bool {
	return v.isSet
}

func (v *NullableFoundContractor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFoundContractor(val *FoundContractor) *NullableFoundContractor {
	return &NullableFoundContractor{value: val, isSet: true}
}

func (v NullableFoundContractor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFoundContractor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


