/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductUnit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductUnit{}

// ProductUnit struct for ProductUnit
type ProductUnit struct {
	// Идентификатор единицы измерения
	Id string `json:"id"`
	// Единица измерения является основной
	IsMain bool `json:"isMain"`
	// Название единицы измерения
	Name string `json:"name"`
	// Соотношение единицы измерения с основной
	Ratio NullableFloat64 `json:"ratio,omitempty"`
}

type _ProductUnit ProductUnit

// NewProductUnit instantiates a new ProductUnit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductUnit(id string, isMain bool, name string) *ProductUnit {
	this := ProductUnit{}
	this.Id = id
	this.IsMain = isMain
	this.Name = name
	return &this
}

// NewProductUnitWithDefaults instantiates a new ProductUnit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductUnitWithDefaults() *ProductUnit {
	this := ProductUnit{}
	return &this
}

// GetId returns the Id field value
func (o *ProductUnit) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProductUnit) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProductUnit) SetId(v string) {
	o.Id = v
}

// GetIsMain returns the IsMain field value
func (o *ProductUnit) GetIsMain() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMain
}

// GetIsMainOk returns a tuple with the IsMain field value
// and a boolean to check if the value has been set.
func (o *ProductUnit) GetIsMainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMain, true
}

// SetIsMain sets field value
func (o *ProductUnit) SetIsMain(v bool) {
	o.IsMain = v
}

// GetName returns the Name field value
func (o *ProductUnit) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductUnit) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductUnit) SetName(v string) {
	o.Name = v
}

// GetRatio returns the Ratio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductUnit) GetRatio() float64 {
	if o == nil || IsNil(o.Ratio.Get()) {
		var ret float64
		return ret
	}
	return *o.Ratio.Get()
}

// GetRatioOk returns a tuple with the Ratio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductUnit) GetRatioOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ratio.Get(), o.Ratio.IsSet()
}

// HasRatio returns a boolean if a field has been set.
func (o *ProductUnit) HasRatio() bool {
	if o != nil && o.Ratio.IsSet() {
		return true
	}

	return false
}

// SetRatio gets a reference to the given NullableFloat64 and assigns it to the Ratio field.
func (o *ProductUnit) SetRatio(v float64) {
	o.Ratio.Set(&v)
}
// SetRatioNil sets the value for Ratio to be an explicit nil
func (o *ProductUnit) SetRatioNil() {
	o.Ratio.Set(nil)
}

// UnsetRatio ensures that no value is present for Ratio, not even an explicit nil
func (o *ProductUnit) UnsetRatio() {
	o.Ratio.Unset()
}

func (o ProductUnit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductUnit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["isMain"] = o.IsMain
	toSerialize["name"] = o.Name
	if o.Ratio.IsSet() {
		toSerialize["ratio"] = o.Ratio.Get()
	}
	return toSerialize, nil
}

func (o *ProductUnit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"isMain",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductUnit := _ProductUnit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductUnit)

	if err != nil {
		return err
	}

	*o = ProductUnit(varProductUnit)

	return err
}

type NullableProductUnit struct {
	value *ProductUnit
	isSet bool
}

func (v NullableProductUnit) Get() *ProductUnit {
	return v.value
}

func (v *NullableProductUnit) Set(val *ProductUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableProductUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableProductUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductUnit(val *ProductUnit) *NullableProductUnit {
	return &NullableProductUnit{value: val, isSet: true}
}

func (v NullableProductUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


