/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"fmt"
)

// CreateProductError   productWithSameNameExists (Уже есть товар с таким названием)
type CreateProductError string

// List of CreateProductError
const (
	ProductWithSameNameExists CreateProductError = "productWithSameNameExists"
)

// All allowed values of CreateProductError enum
var AllowedCreateProductErrorEnumValues = []CreateProductError{
	"productWithSameNameExists",
}

func (v *CreateProductError) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CreateProductError(value)
	for _, existing := range AllowedCreateProductErrorEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CreateProductError", value)
}

// NewCreateProductErrorFromValue returns a pointer to a valid CreateProductError
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCreateProductErrorFromValue(v string) (*CreateProductError, error) {
	ev := CreateProductError(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CreateProductError: valid values are %v", v, AllowedCreateProductErrorEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CreateProductError) IsValid() bool {
	for _, existing := range AllowedCreateProductErrorEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CreateProductError value
func (v CreateProductError) Ptr() *CreateProductError {
	return &v
}

type NullableCreateProductError struct {
	value *CreateProductError
	isSet bool
}

func (v NullableCreateProductError) Get() *CreateProductError {
	return v.value
}

func (v *NullableCreateProductError) Set(val *CreateProductError) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductError) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductError(val *CreateProductError) *NullableCreateProductError {
	return &NullableCreateProductError{value: val, isSet: true}
}

func (v NullableCreateProductError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

