/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"fmt"
)

// NewsType   billPaymentNews
type NewsType string

// List of NewsType
const (
	BillPaymentNews NewsType = "billPaymentNews"
)

// All allowed values of NewsType enum
var AllowedNewsTypeEnumValues = []NewsType{
	"billPaymentNews",
}

func (v *NewsType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NewsType(value)
	for _, existing := range AllowedNewsTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NewsType", value)
}

// NewNewsTypeFromValue returns a pointer to a valid NewsType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNewsTypeFromValue(v string) (*NewsType, error) {
	ev := NewsType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NewsType: valid values are %v", v, AllowedNewsTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NewsType) IsValid() bool {
	for _, existing := range AllowedNewsTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NewsType value
func (v NewsType) Ptr() *NewsType {
	return &v
}

type NullableNewsType struct {
	value *NewsType
	isSet bool
}

func (v NullableNewsType) Get() *NewsType {
	return v.value
}

func (v *NullableNewsType) Set(val *NewsType) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsType) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsType(val *NewsType) *NullableNewsType {
	return &NullableNewsType{value: val, isSet: true}
}

func (v NullableNewsType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

