/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FoundProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FoundProduct{}

// FoundProduct struct for FoundProduct
type FoundProduct struct {
	// Идентификатор товара
	Id string `json:"id"`
	// Главное название товара
	ProductMainName string `json:"productMainName"`
	// Артикул
	Article NullableString `json:"article,omitempty"`
}

type _FoundProduct FoundProduct

// NewFoundProduct instantiates a new FoundProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFoundProduct(id string, productMainName string) *FoundProduct {
	this := FoundProduct{}
	this.Id = id
	this.ProductMainName = productMainName
	return &this
}

// NewFoundProductWithDefaults instantiates a new FoundProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFoundProductWithDefaults() *FoundProduct {
	this := FoundProduct{}
	return &this
}

// GetId returns the Id field value
func (o *FoundProduct) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FoundProduct) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FoundProduct) SetId(v string) {
	o.Id = v
}

// GetProductMainName returns the ProductMainName field value
func (o *FoundProduct) GetProductMainName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductMainName
}

// GetProductMainNameOk returns a tuple with the ProductMainName field value
// and a boolean to check if the value has been set.
func (o *FoundProduct) GetProductMainNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductMainName, true
}

// SetProductMainName sets field value
func (o *FoundProduct) SetProductMainName(v string) {
	o.ProductMainName = v
}

// GetArticle returns the Article field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FoundProduct) GetArticle() string {
	if o == nil || IsNil(o.Article.Get()) {
		var ret string
		return ret
	}
	return *o.Article.Get()
}

// GetArticleOk returns a tuple with the Article field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FoundProduct) GetArticleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Article.Get(), o.Article.IsSet()
}

// HasArticle returns a boolean if a field has been set.
func (o *FoundProduct) HasArticle() bool {
	if o != nil && o.Article.IsSet() {
		return true
	}

	return false
}

// SetArticle gets a reference to the given NullableString and assigns it to the Article field.
func (o *FoundProduct) SetArticle(v string) {
	o.Article.Set(&v)
}
// SetArticleNil sets the value for Article to be an explicit nil
func (o *FoundProduct) SetArticleNil() {
	o.Article.Set(nil)
}

// UnsetArticle ensures that no value is present for Article, not even an explicit nil
func (o *FoundProduct) UnsetArticle() {
	o.Article.Unset()
}

func (o FoundProduct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FoundProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["productMainName"] = o.ProductMainName
	if o.Article.IsSet() {
		toSerialize["article"] = o.Article.Get()
	}
	return toSerialize, nil
}

func (o *FoundProduct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"productMainName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFoundProduct := _FoundProduct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFoundProduct)

	if err != nil {
		return err
	}

	*o = FoundProduct(varFoundProduct)

	return err
}

type NullableFoundProduct struct {
	value *FoundProduct
	isSet bool
}

func (v NullableFoundProduct) Get() *FoundProduct {
	return v.value
}

func (v *NullableFoundProduct) Set(val *FoundProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableFoundProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableFoundProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFoundProduct(val *FoundProduct) *NullableFoundProduct {
	return &NullableFoundProduct{value: val, isSet: true}
}

func (v NullableFoundProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFoundProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


