/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AcceptedLongRunningTask type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AcceptedLongRunningTask{}

// AcceptedLongRunningTask struct for AcceptedLongRunningTask
type AcceptedLongRunningTask struct {
	// Идентификатор асинхронной операции
	Id string `json:"id"`
	// Статус асинхронной операции  inProcess (Операция в обработке)  completed (Операция успешно обработана)  failed (Ошибка при выполнении операции)
	Status LongRunningTaskStatus `json:"status"`
	// Тип задачи  searchContractors (Операция поиска контрагентов)  searchProducts (Операция поиска товаров)  createProduct (Операция создания товара)  updateProduct (Операция обновления товара)
	Type LongRunningTaskType `json:"type"`
}

type _AcceptedLongRunningTask AcceptedLongRunningTask

// NewAcceptedLongRunningTask instantiates a new AcceptedLongRunningTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcceptedLongRunningTask(id string, status LongRunningTaskStatus, type_ LongRunningTaskType) *AcceptedLongRunningTask {
	this := AcceptedLongRunningTask{}
	this.Id = id
	this.Status = status
	this.Type = type_
	return &this
}

// NewAcceptedLongRunningTaskWithDefaults instantiates a new AcceptedLongRunningTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcceptedLongRunningTaskWithDefaults() *AcceptedLongRunningTask {
	this := AcceptedLongRunningTask{}
	return &this
}

// GetId returns the Id field value
func (o *AcceptedLongRunningTask) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AcceptedLongRunningTask) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AcceptedLongRunningTask) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *AcceptedLongRunningTask) GetStatus() LongRunningTaskStatus {
	if o == nil {
		var ret LongRunningTaskStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AcceptedLongRunningTask) GetStatusOk() (*LongRunningTaskStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AcceptedLongRunningTask) SetStatus(v LongRunningTaskStatus) {
	o.Status = v
}

// GetType returns the Type field value
func (o *AcceptedLongRunningTask) GetType() LongRunningTaskType {
	if o == nil {
		var ret LongRunningTaskType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AcceptedLongRunningTask) GetTypeOk() (*LongRunningTaskType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AcceptedLongRunningTask) SetType(v LongRunningTaskType) {
	o.Type = v
}

func (o AcceptedLongRunningTask) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AcceptedLongRunningTask) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *AcceptedLongRunningTask) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAcceptedLongRunningTask := _AcceptedLongRunningTask{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAcceptedLongRunningTask)

	if err != nil {
		return err
	}

	*o = AcceptedLongRunningTask(varAcceptedLongRunningTask)

	return err
}

type NullableAcceptedLongRunningTask struct {
	value *AcceptedLongRunningTask
	isSet bool
}

func (v NullableAcceptedLongRunningTask) Get() *AcceptedLongRunningTask {
	return v.value
}

func (v *NullableAcceptedLongRunningTask) Set(val *AcceptedLongRunningTask) {
	v.value = val
	v.isSet = true
}

func (v NullableAcceptedLongRunningTask) IsSet() bool {
	return v.isSet
}

func (v *NullableAcceptedLongRunningTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcceptedLongRunningTask(val *AcceptedLongRunningTask) *NullableAcceptedLongRunningTask {
	return &NullableAcceptedLongRunningTask{value: val, isSet: true}
}

func (v NullableAcceptedLongRunningTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcceptedLongRunningTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


