/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetBankAccountsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBankAccountsResponse{}

// GetBankAccountsResponse struct for GetBankAccountsResponse
type GetBankAccountsResponse struct {
	// Список банковских счетов
	BankAccounts []BankAccount `json:"bankAccounts"`
}

type _GetBankAccountsResponse GetBankAccountsResponse

// NewGetBankAccountsResponse instantiates a new GetBankAccountsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBankAccountsResponse(bankAccounts []BankAccount) *GetBankAccountsResponse {
	this := GetBankAccountsResponse{}
	this.BankAccounts = bankAccounts
	return &this
}

// NewGetBankAccountsResponseWithDefaults instantiates a new GetBankAccountsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBankAccountsResponseWithDefaults() *GetBankAccountsResponse {
	this := GetBankAccountsResponse{}
	return &this
}

// GetBankAccounts returns the BankAccounts field value
func (o *GetBankAccountsResponse) GetBankAccounts() []BankAccount {
	if o == nil {
		var ret []BankAccount
		return ret
	}

	return o.BankAccounts
}

// GetBankAccountsOk returns a tuple with the BankAccounts field value
// and a boolean to check if the value has been set.
func (o *GetBankAccountsResponse) GetBankAccountsOk() ([]BankAccount, bool) {
	if o == nil {
		return nil, false
	}
	return o.BankAccounts, true
}

// SetBankAccounts sets field value
func (o *GetBankAccountsResponse) SetBankAccounts(v []BankAccount) {
	o.BankAccounts = v
}

func (o GetBankAccountsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBankAccountsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bankAccounts"] = o.BankAccounts
	return toSerialize, nil
}

func (o *GetBankAccountsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bankAccounts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetBankAccountsResponse := _GetBankAccountsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetBankAccountsResponse)

	if err != nil {
		return err
	}

	*o = GetBankAccountsResponse(varGetBankAccountsResponse)

	return err
}

type NullableGetBankAccountsResponse struct {
	value *GetBankAccountsResponse
	isSet bool
}

func (v NullableGetBankAccountsResponse) Get() *GetBankAccountsResponse {
	return v.value
}

func (v *NullableGetBankAccountsResponse) Set(val *GetBankAccountsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBankAccountsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBankAccountsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBankAccountsResponse(val *GetBankAccountsResponse) *NullableGetBankAccountsResponse {
	return &NullableGetBankAccountsResponse{value: val, isSet: true}
}

func (v NullableGetBankAccountsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBankAccountsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


