/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDeliveryNoteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDeliveryNoteRequest{}

// CreateDeliveryNoteRequest struct for CreateDeliveryNoteRequest
type CreateDeliveryNoteRequest struct {
	// Номер накладной. Если номер не указан, то номер будет сгенерирован Эльбой
	Number NullableString `json:"number,omitempty"`
	// Дата накладной
	Date string `json:"date"`
	// Ндс
	WithNDS NullableBool `json:"withNDS,omitempty"`
	// Идентификатор банковского счёта
	BankAccountId NullableString `json:"bankAccountId,omitempty"`
	// Идентификатор контрагента
	ContractorId NullableString `json:"contractorId,omitempty"`
	// Цена за единицу товара включает в себя НДС
	SumsWithNDS NullableBool `json:"sumsWithNDS,omitempty"`
	// Идентификатор грузополучателя
	ConsigneeId NullableString `json:"consigneeId,omitempty"`
	// Основание
	ReasonName NullableString `json:"reasonName,omitempty"`
	// Дата основания
	ReasonDate NullableString `json:"reasonDate,omitempty"`
	// Выставить накладную со скидкой
	WithDiscount NullableBool `json:"withDiscount,omitempty"`
	// Фактурная часть
	WarehouseItems []DeliveryNoteItemToCreate `json:"warehouseItems,omitempty"`
}

type _CreateDeliveryNoteRequest CreateDeliveryNoteRequest

// NewCreateDeliveryNoteRequest instantiates a new CreateDeliveryNoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeliveryNoteRequest(date string) *CreateDeliveryNoteRequest {
	this := CreateDeliveryNoteRequest{}
	this.Date = date
	return &this
}

// NewCreateDeliveryNoteRequestWithDefaults instantiates a new CreateDeliveryNoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeliveryNoteRequestWithDefaults() *CreateDeliveryNoteRequest {
	this := CreateDeliveryNoteRequest{}
	return &this
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetNumber() string {
	if o == nil || IsNil(o.Number.Get()) {
		var ret string
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableString and assigns it to the Number field.
func (o *CreateDeliveryNoteRequest) SetNumber(v string) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetNumber() {
	o.Number.Unset()
}

// GetDate returns the Date field value
func (o *CreateDeliveryNoteRequest) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *CreateDeliveryNoteRequest) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *CreateDeliveryNoteRequest) SetDate(v string) {
	o.Date = v
}

// GetWithNDS returns the WithNDS field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetWithNDS() bool {
	if o == nil || IsNil(o.WithNDS.Get()) {
		var ret bool
		return ret
	}
	return *o.WithNDS.Get()
}

// GetWithNDSOk returns a tuple with the WithNDS field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetWithNDSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WithNDS.Get(), o.WithNDS.IsSet()
}

// HasWithNDS returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasWithNDS() bool {
	if o != nil && o.WithNDS.IsSet() {
		return true
	}

	return false
}

// SetWithNDS gets a reference to the given NullableBool and assigns it to the WithNDS field.
func (o *CreateDeliveryNoteRequest) SetWithNDS(v bool) {
	o.WithNDS.Set(&v)
}
// SetWithNDSNil sets the value for WithNDS to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetWithNDSNil() {
	o.WithNDS.Set(nil)
}

// UnsetWithNDS ensures that no value is present for WithNDS, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetWithNDS() {
	o.WithNDS.Unset()
}

// GetBankAccountId returns the BankAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetBankAccountId() string {
	if o == nil || IsNil(o.BankAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.BankAccountId.Get()
}

// GetBankAccountIdOk returns a tuple with the BankAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetBankAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BankAccountId.Get(), o.BankAccountId.IsSet()
}

// HasBankAccountId returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasBankAccountId() bool {
	if o != nil && o.BankAccountId.IsSet() {
		return true
	}

	return false
}

// SetBankAccountId gets a reference to the given NullableString and assigns it to the BankAccountId field.
func (o *CreateDeliveryNoteRequest) SetBankAccountId(v string) {
	o.BankAccountId.Set(&v)
}
// SetBankAccountIdNil sets the value for BankAccountId to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetBankAccountIdNil() {
	o.BankAccountId.Set(nil)
}

// UnsetBankAccountId ensures that no value is present for BankAccountId, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetBankAccountId() {
	o.BankAccountId.Unset()
}

// GetContractorId returns the ContractorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetContractorId() string {
	if o == nil || IsNil(o.ContractorId.Get()) {
		var ret string
		return ret
	}
	return *o.ContractorId.Get()
}

// GetContractorIdOk returns a tuple with the ContractorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetContractorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContractorId.Get(), o.ContractorId.IsSet()
}

// HasContractorId returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasContractorId() bool {
	if o != nil && o.ContractorId.IsSet() {
		return true
	}

	return false
}

// SetContractorId gets a reference to the given NullableString and assigns it to the ContractorId field.
func (o *CreateDeliveryNoteRequest) SetContractorId(v string) {
	o.ContractorId.Set(&v)
}
// SetContractorIdNil sets the value for ContractorId to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetContractorIdNil() {
	o.ContractorId.Set(nil)
}

// UnsetContractorId ensures that no value is present for ContractorId, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetContractorId() {
	o.ContractorId.Unset()
}

// GetSumsWithNDS returns the SumsWithNDS field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetSumsWithNDS() bool {
	if o == nil || IsNil(o.SumsWithNDS.Get()) {
		var ret bool
		return ret
	}
	return *o.SumsWithNDS.Get()
}

// GetSumsWithNDSOk returns a tuple with the SumsWithNDS field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetSumsWithNDSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SumsWithNDS.Get(), o.SumsWithNDS.IsSet()
}

// HasSumsWithNDS returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasSumsWithNDS() bool {
	if o != nil && o.SumsWithNDS.IsSet() {
		return true
	}

	return false
}

// SetSumsWithNDS gets a reference to the given NullableBool and assigns it to the SumsWithNDS field.
func (o *CreateDeliveryNoteRequest) SetSumsWithNDS(v bool) {
	o.SumsWithNDS.Set(&v)
}
// SetSumsWithNDSNil sets the value for SumsWithNDS to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetSumsWithNDSNil() {
	o.SumsWithNDS.Set(nil)
}

// UnsetSumsWithNDS ensures that no value is present for SumsWithNDS, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetSumsWithNDS() {
	o.SumsWithNDS.Unset()
}

// GetConsigneeId returns the ConsigneeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetConsigneeId() string {
	if o == nil || IsNil(o.ConsigneeId.Get()) {
		var ret string
		return ret
	}
	return *o.ConsigneeId.Get()
}

// GetConsigneeIdOk returns a tuple with the ConsigneeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetConsigneeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsigneeId.Get(), o.ConsigneeId.IsSet()
}

// HasConsigneeId returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasConsigneeId() bool {
	if o != nil && o.ConsigneeId.IsSet() {
		return true
	}

	return false
}

// SetConsigneeId gets a reference to the given NullableString and assigns it to the ConsigneeId field.
func (o *CreateDeliveryNoteRequest) SetConsigneeId(v string) {
	o.ConsigneeId.Set(&v)
}
// SetConsigneeIdNil sets the value for ConsigneeId to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetConsigneeIdNil() {
	o.ConsigneeId.Set(nil)
}

// UnsetConsigneeId ensures that no value is present for ConsigneeId, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetConsigneeId() {
	o.ConsigneeId.Unset()
}

// GetReasonName returns the ReasonName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetReasonName() string {
	if o == nil || IsNil(o.ReasonName.Get()) {
		var ret string
		return ret
	}
	return *o.ReasonName.Get()
}

// GetReasonNameOk returns a tuple with the ReasonName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetReasonNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReasonName.Get(), o.ReasonName.IsSet()
}

// HasReasonName returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasReasonName() bool {
	if o != nil && o.ReasonName.IsSet() {
		return true
	}

	return false
}

// SetReasonName gets a reference to the given NullableString and assigns it to the ReasonName field.
func (o *CreateDeliveryNoteRequest) SetReasonName(v string) {
	o.ReasonName.Set(&v)
}
// SetReasonNameNil sets the value for ReasonName to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetReasonNameNil() {
	o.ReasonName.Set(nil)
}

// UnsetReasonName ensures that no value is present for ReasonName, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetReasonName() {
	o.ReasonName.Unset()
}

// GetReasonDate returns the ReasonDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetReasonDate() string {
	if o == nil || IsNil(o.ReasonDate.Get()) {
		var ret string
		return ret
	}
	return *o.ReasonDate.Get()
}

// GetReasonDateOk returns a tuple with the ReasonDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetReasonDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReasonDate.Get(), o.ReasonDate.IsSet()
}

// HasReasonDate returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasReasonDate() bool {
	if o != nil && o.ReasonDate.IsSet() {
		return true
	}

	return false
}

// SetReasonDate gets a reference to the given NullableString and assigns it to the ReasonDate field.
func (o *CreateDeliveryNoteRequest) SetReasonDate(v string) {
	o.ReasonDate.Set(&v)
}
// SetReasonDateNil sets the value for ReasonDate to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetReasonDateNil() {
	o.ReasonDate.Set(nil)
}

// UnsetReasonDate ensures that no value is present for ReasonDate, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetReasonDate() {
	o.ReasonDate.Unset()
}

// GetWithDiscount returns the WithDiscount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetWithDiscount() bool {
	if o == nil || IsNil(o.WithDiscount.Get()) {
		var ret bool
		return ret
	}
	return *o.WithDiscount.Get()
}

// GetWithDiscountOk returns a tuple with the WithDiscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetWithDiscountOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WithDiscount.Get(), o.WithDiscount.IsSet()
}

// HasWithDiscount returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasWithDiscount() bool {
	if o != nil && o.WithDiscount.IsSet() {
		return true
	}

	return false
}

// SetWithDiscount gets a reference to the given NullableBool and assigns it to the WithDiscount field.
func (o *CreateDeliveryNoteRequest) SetWithDiscount(v bool) {
	o.WithDiscount.Set(&v)
}
// SetWithDiscountNil sets the value for WithDiscount to be an explicit nil
func (o *CreateDeliveryNoteRequest) SetWithDiscountNil() {
	o.WithDiscount.Set(nil)
}

// UnsetWithDiscount ensures that no value is present for WithDiscount, not even an explicit nil
func (o *CreateDeliveryNoteRequest) UnsetWithDiscount() {
	o.WithDiscount.Unset()
}

// GetWarehouseItems returns the WarehouseItems field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDeliveryNoteRequest) GetWarehouseItems() []DeliveryNoteItemToCreate {
	if o == nil {
		var ret []DeliveryNoteItemToCreate
		return ret
	}
	return o.WarehouseItems
}

// GetWarehouseItemsOk returns a tuple with the WarehouseItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDeliveryNoteRequest) GetWarehouseItemsOk() ([]DeliveryNoteItemToCreate, bool) {
	if o == nil || IsNil(o.WarehouseItems) {
		return nil, false
	}
	return o.WarehouseItems, true
}

// HasWarehouseItems returns a boolean if a field has been set.
func (o *CreateDeliveryNoteRequest) HasWarehouseItems() bool {
	if o != nil && !IsNil(o.WarehouseItems) {
		return true
	}

	return false
}

// SetWarehouseItems gets a reference to the given []DeliveryNoteItemToCreate and assigns it to the WarehouseItems field.
func (o *CreateDeliveryNoteRequest) SetWarehouseItems(v []DeliveryNoteItemToCreate) {
	o.WarehouseItems = v
}

func (o CreateDeliveryNoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDeliveryNoteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	toSerialize["date"] = o.Date
	if o.WithNDS.IsSet() {
		toSerialize["withNDS"] = o.WithNDS.Get()
	}
	if o.BankAccountId.IsSet() {
		toSerialize["bankAccountId"] = o.BankAccountId.Get()
	}
	if o.ContractorId.IsSet() {
		toSerialize["contractorId"] = o.ContractorId.Get()
	}
	if o.SumsWithNDS.IsSet() {
		toSerialize["sumsWithNDS"] = o.SumsWithNDS.Get()
	}
	if o.ConsigneeId.IsSet() {
		toSerialize["consigneeId"] = o.ConsigneeId.Get()
	}
	if o.ReasonName.IsSet() {
		toSerialize["reasonName"] = o.ReasonName.Get()
	}
	if o.ReasonDate.IsSet() {
		toSerialize["reasonDate"] = o.ReasonDate.Get()
	}
	if o.WithDiscount.IsSet() {
		toSerialize["withDiscount"] = o.WithDiscount.Get()
	}
	if o.WarehouseItems != nil {
		toSerialize["warehouseItems"] = o.WarehouseItems
	}
	return toSerialize, nil
}

func (o *CreateDeliveryNoteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDeliveryNoteRequest := _CreateDeliveryNoteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDeliveryNoteRequest)

	if err != nil {
		return err
	}

	*o = CreateDeliveryNoteRequest(varCreateDeliveryNoteRequest)

	return err
}

type NullableCreateDeliveryNoteRequest struct {
	value *CreateDeliveryNoteRequest
	isSet bool
}

func (v NullableCreateDeliveryNoteRequest) Get() *CreateDeliveryNoteRequest {
	return v.value
}

func (v *NullableCreateDeliveryNoteRequest) Set(val *CreateDeliveryNoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeliveryNoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeliveryNoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeliveryNoteRequest(val *CreateDeliveryNoteRequest) *NullableCreateDeliveryNoteRequest {
	return &NullableCreateDeliveryNoteRequest{value: val, isSet: true}
}

func (v NullableCreateDeliveryNoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeliveryNoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


