/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBillRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBillRequest{}

// CreateBillRequest struct for CreateBillRequest
type CreateBillRequest struct {
	// Номер счёта. Если номер не указан, то номер будет сгенерирован Эльбой
	Number NullableString `json:"number,omitempty"`
	// Дата счёта
	Date string `json:"date"`
	// Ндс
	WithNDS NullableBool `json:"withNDS,omitempty"`
	// Комментарий
	Comment NullableString `json:"comment,omitempty"`
	// Идентификатор банковского счёта
	BankAccountId NullableString `json:"bankAccountId,omitempty"`
	// Идентификатор контрагента
	ContractorId NullableString `json:"contractorId,omitempty"`
	// Цена за единицу товара включает в себя НДС
	SumsWithNDS NullableBool `json:"sumsWithNDS,omitempty"`
	// Выставить счёт со скидкой
	WithDiscount NullableBool `json:"withDiscount,omitempty"`
	// Фактурная часть
	WarehouseItems []BillItemToCreate `json:"warehouseItems,omitempty"`
}

type _CreateBillRequest CreateBillRequest

// NewCreateBillRequest instantiates a new CreateBillRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBillRequest(date string) *CreateBillRequest {
	this := CreateBillRequest{}
	this.Date = date
	return &this
}

// NewCreateBillRequestWithDefaults instantiates a new CreateBillRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBillRequestWithDefaults() *CreateBillRequest {
	this := CreateBillRequest{}
	return &this
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBillRequest) GetNumber() string {
	if o == nil || IsNil(o.Number.Get()) {
		var ret string
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBillRequest) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *CreateBillRequest) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableString and assigns it to the Number field.
func (o *CreateBillRequest) SetNumber(v string) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *CreateBillRequest) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *CreateBillRequest) UnsetNumber() {
	o.Number.Unset()
}

// GetDate returns the Date field value
func (o *CreateBillRequest) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *CreateBillRequest) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *CreateBillRequest) SetDate(v string) {
	o.Date = v
}

// GetWithNDS returns the WithNDS field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBillRequest) GetWithNDS() bool {
	if o == nil || IsNil(o.WithNDS.Get()) {
		var ret bool
		return ret
	}
	return *o.WithNDS.Get()
}

// GetWithNDSOk returns a tuple with the WithNDS field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBillRequest) GetWithNDSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WithNDS.Get(), o.WithNDS.IsSet()
}

// HasWithNDS returns a boolean if a field has been set.
func (o *CreateBillRequest) HasWithNDS() bool {
	if o != nil && o.WithNDS.IsSet() {
		return true
	}

	return false
}

// SetWithNDS gets a reference to the given NullableBool and assigns it to the WithNDS field.
func (o *CreateBillRequest) SetWithNDS(v bool) {
	o.WithNDS.Set(&v)
}
// SetWithNDSNil sets the value for WithNDS to be an explicit nil
func (o *CreateBillRequest) SetWithNDSNil() {
	o.WithNDS.Set(nil)
}

// UnsetWithNDS ensures that no value is present for WithNDS, not even an explicit nil
func (o *CreateBillRequest) UnsetWithNDS() {
	o.WithNDS.Unset()
}

// GetComment returns the Comment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBillRequest) GetComment() string {
	if o == nil || IsNil(o.Comment.Get()) {
		var ret string
		return ret
	}
	return *o.Comment.Get()
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBillRequest) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Comment.Get(), o.Comment.IsSet()
}

// HasComment returns a boolean if a field has been set.
func (o *CreateBillRequest) HasComment() bool {
	if o != nil && o.Comment.IsSet() {
		return true
	}

	return false
}

// SetComment gets a reference to the given NullableString and assigns it to the Comment field.
func (o *CreateBillRequest) SetComment(v string) {
	o.Comment.Set(&v)
}
// SetCommentNil sets the value for Comment to be an explicit nil
func (o *CreateBillRequest) SetCommentNil() {
	o.Comment.Set(nil)
}

// UnsetComment ensures that no value is present for Comment, not even an explicit nil
func (o *CreateBillRequest) UnsetComment() {
	o.Comment.Unset()
}

// GetBankAccountId returns the BankAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBillRequest) GetBankAccountId() string {
	if o == nil || IsNil(o.BankAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.BankAccountId.Get()
}

// GetBankAccountIdOk returns a tuple with the BankAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBillRequest) GetBankAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BankAccountId.Get(), o.BankAccountId.IsSet()
}

// HasBankAccountId returns a boolean if a field has been set.
func (o *CreateBillRequest) HasBankAccountId() bool {
	if o != nil && o.BankAccountId.IsSet() {
		return true
	}

	return false
}

// SetBankAccountId gets a reference to the given NullableString and assigns it to the BankAccountId field.
func (o *CreateBillRequest) SetBankAccountId(v string) {
	o.BankAccountId.Set(&v)
}
// SetBankAccountIdNil sets the value for BankAccountId to be an explicit nil
func (o *CreateBillRequest) SetBankAccountIdNil() {
	o.BankAccountId.Set(nil)
}

// UnsetBankAccountId ensures that no value is present for BankAccountId, not even an explicit nil
func (o *CreateBillRequest) UnsetBankAccountId() {
	o.BankAccountId.Unset()
}

// GetContractorId returns the ContractorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBillRequest) GetContractorId() string {
	if o == nil || IsNil(o.ContractorId.Get()) {
		var ret string
		return ret
	}
	return *o.ContractorId.Get()
}

// GetContractorIdOk returns a tuple with the ContractorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBillRequest) GetContractorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContractorId.Get(), o.ContractorId.IsSet()
}

// HasContractorId returns a boolean if a field has been set.
func (o *CreateBillRequest) HasContractorId() bool {
	if o != nil && o.ContractorId.IsSet() {
		return true
	}

	return false
}

// SetContractorId gets a reference to the given NullableString and assigns it to the ContractorId field.
func (o *CreateBillRequest) SetContractorId(v string) {
	o.ContractorId.Set(&v)
}
// SetContractorIdNil sets the value for ContractorId to be an explicit nil
func (o *CreateBillRequest) SetContractorIdNil() {
	o.ContractorId.Set(nil)
}

// UnsetContractorId ensures that no value is present for ContractorId, not even an explicit nil
func (o *CreateBillRequest) UnsetContractorId() {
	o.ContractorId.Unset()
}

// GetSumsWithNDS returns the SumsWithNDS field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBillRequest) GetSumsWithNDS() bool {
	if o == nil || IsNil(o.SumsWithNDS.Get()) {
		var ret bool
		return ret
	}
	return *o.SumsWithNDS.Get()
}

// GetSumsWithNDSOk returns a tuple with the SumsWithNDS field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBillRequest) GetSumsWithNDSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SumsWithNDS.Get(), o.SumsWithNDS.IsSet()
}

// HasSumsWithNDS returns a boolean if a field has been set.
func (o *CreateBillRequest) HasSumsWithNDS() bool {
	if o != nil && o.SumsWithNDS.IsSet() {
		return true
	}

	return false
}

// SetSumsWithNDS gets a reference to the given NullableBool and assigns it to the SumsWithNDS field.
func (o *CreateBillRequest) SetSumsWithNDS(v bool) {
	o.SumsWithNDS.Set(&v)
}
// SetSumsWithNDSNil sets the value for SumsWithNDS to be an explicit nil
func (o *CreateBillRequest) SetSumsWithNDSNil() {
	o.SumsWithNDS.Set(nil)
}

// UnsetSumsWithNDS ensures that no value is present for SumsWithNDS, not even an explicit nil
func (o *CreateBillRequest) UnsetSumsWithNDS() {
	o.SumsWithNDS.Unset()
}

// GetWithDiscount returns the WithDiscount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBillRequest) GetWithDiscount() bool {
	if o == nil || IsNil(o.WithDiscount.Get()) {
		var ret bool
		return ret
	}
	return *o.WithDiscount.Get()
}

// GetWithDiscountOk returns a tuple with the WithDiscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBillRequest) GetWithDiscountOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WithDiscount.Get(), o.WithDiscount.IsSet()
}

// HasWithDiscount returns a boolean if a field has been set.
func (o *CreateBillRequest) HasWithDiscount() bool {
	if o != nil && o.WithDiscount.IsSet() {
		return true
	}

	return false
}

// SetWithDiscount gets a reference to the given NullableBool and assigns it to the WithDiscount field.
func (o *CreateBillRequest) SetWithDiscount(v bool) {
	o.WithDiscount.Set(&v)
}
// SetWithDiscountNil sets the value for WithDiscount to be an explicit nil
func (o *CreateBillRequest) SetWithDiscountNil() {
	o.WithDiscount.Set(nil)
}

// UnsetWithDiscount ensures that no value is present for WithDiscount, not even an explicit nil
func (o *CreateBillRequest) UnsetWithDiscount() {
	o.WithDiscount.Unset()
}

// GetWarehouseItems returns the WarehouseItems field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBillRequest) GetWarehouseItems() []BillItemToCreate {
	if o == nil {
		var ret []BillItemToCreate
		return ret
	}
	return o.WarehouseItems
}

// GetWarehouseItemsOk returns a tuple with the WarehouseItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBillRequest) GetWarehouseItemsOk() ([]BillItemToCreate, bool) {
	if o == nil || IsNil(o.WarehouseItems) {
		return nil, false
	}
	return o.WarehouseItems, true
}

// HasWarehouseItems returns a boolean if a field has been set.
func (o *CreateBillRequest) HasWarehouseItems() bool {
	if o != nil && !IsNil(o.WarehouseItems) {
		return true
	}

	return false
}

// SetWarehouseItems gets a reference to the given []BillItemToCreate and assigns it to the WarehouseItems field.
func (o *CreateBillRequest) SetWarehouseItems(v []BillItemToCreate) {
	o.WarehouseItems = v
}

func (o CreateBillRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBillRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	toSerialize["date"] = o.Date
	if o.WithNDS.IsSet() {
		toSerialize["withNDS"] = o.WithNDS.Get()
	}
	if o.Comment.IsSet() {
		toSerialize["comment"] = o.Comment.Get()
	}
	if o.BankAccountId.IsSet() {
		toSerialize["bankAccountId"] = o.BankAccountId.Get()
	}
	if o.ContractorId.IsSet() {
		toSerialize["contractorId"] = o.ContractorId.Get()
	}
	if o.SumsWithNDS.IsSet() {
		toSerialize["sumsWithNDS"] = o.SumsWithNDS.Get()
	}
	if o.WithDiscount.IsSet() {
		toSerialize["withDiscount"] = o.WithDiscount.Get()
	}
	if o.WarehouseItems != nil {
		toSerialize["warehouseItems"] = o.WarehouseItems
	}
	return toSerialize, nil
}

func (o *CreateBillRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBillRequest := _CreateBillRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBillRequest)

	if err != nil {
		return err
	}

	*o = CreateBillRequest(varCreateBillRequest)

	return err
}

type NullableCreateBillRequest struct {
	value *CreateBillRequest
	isSet bool
}

func (v NullableCreateBillRequest) Get() *CreateBillRequest {
	return v.value
}

func (v *NullableCreateBillRequest) Set(val *CreateBillRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBillRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBillRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBillRequest(val *CreateBillRequest) *NullableCreateBillRequest {
	return &NullableCreateBillRequest{value: val, isSet: true}
}

func (v NullableCreateBillRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBillRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


