/*
Elba Public API

  ## С чего начать    Для работы с API нужно выпустить API-ключ — уникальный токен, позволяющий авторизовывать ваши запросы в API Контур.Эльбы.    #### Как получить API-ключ    1. Откройте Эльбу, в верхнем правом углу нажмите «Настройки и оплата» → «Настройки сервиса».  2. Перейдите на вкладку «API».  2. Нажмите на кнопку «Выпустить ключ». После этого откроется окно со сгенерированным API-ключом.  3. В открывшемся окне появится ваш API-ключ. Скопируйте и сохраните его в надежном месте, потому что он будет показан только один раз. Это сделано в целях безопасности — мы не храним ключи на своей стороне.

API version: v1
Contact: e@kontur.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package elba

import (
	"encoding/json"
	"fmt"
)

// UniversalTransferDocumentStatus   status1 (Со счётом-фактурой, то есть с НДС)  status2 (Без счёта-фактуры)
type UniversalTransferDocumentStatus string

// List of UniversalTransferDocumentStatus
const (
	Status1 UniversalTransferDocumentStatus = "status1"
	Status2 UniversalTransferDocumentStatus = "status2"
)

// All allowed values of UniversalTransferDocumentStatus enum
var AllowedUniversalTransferDocumentStatusEnumValues = []UniversalTransferDocumentStatus{
	"status1",
	"status2",
}

func (v *UniversalTransferDocumentStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UniversalTransferDocumentStatus(value)
	for _, existing := range AllowedUniversalTransferDocumentStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UniversalTransferDocumentStatus", value)
}

// NewUniversalTransferDocumentStatusFromValue returns a pointer to a valid UniversalTransferDocumentStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUniversalTransferDocumentStatusFromValue(v string) (*UniversalTransferDocumentStatus, error) {
	ev := UniversalTransferDocumentStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UniversalTransferDocumentStatus: valid values are %v", v, AllowedUniversalTransferDocumentStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UniversalTransferDocumentStatus) IsValid() bool {
	for _, existing := range AllowedUniversalTransferDocumentStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UniversalTransferDocumentStatus value
func (v UniversalTransferDocumentStatus) Ptr() *UniversalTransferDocumentStatus {
	return &v
}

type NullableUniversalTransferDocumentStatus struct {
	value *UniversalTransferDocumentStatus
	isSet bool
}

func (v NullableUniversalTransferDocumentStatus) Get() *UniversalTransferDocumentStatus {
	return v.value
}

func (v *NullableUniversalTransferDocumentStatus) Set(val *UniversalTransferDocumentStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUniversalTransferDocumentStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUniversalTransferDocumentStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUniversalTransferDocumentStatus(val *UniversalTransferDocumentStatus) *NullableUniversalTransferDocumentStatus {
	return &NullableUniversalTransferDocumentStatus{value: val, isSet: true}
}

func (v NullableUniversalTransferDocumentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUniversalTransferDocumentStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

